# Generated by Django 3.1.4 on 2021-02-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grid", "0002_auto_20210115_2341"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObtainDOI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="projects",
            name="obtain_doi_other",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="obtain_doi",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grid.obtaindoi",
            ),
        ),
    ]
